[workspace]
name = "imetro_behavior"
authors = ["Sebastian Castro <sebastian.a.castrofernandez@nasa.gov>"]
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"
channels = [
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
]

[activation]
scripts = ["scripts/entrypoint.sh"]

[activation.env]
COLCON_DEFAULT_OUTPUT_STYLE = "catkin_tools"
COLCON_DEFAULTS_FILE = "${PIXI_PROJECT_ROOT}/config/colcon-defaults.yaml"
RCUTILS_COLORIZED_OUTPUT = "1"

[tasks]
build = "colcon build --cmake-args"
test = "colcon test"
clean = "rm -rf build/* install/* log/*"

[dependencies]
# Python dependencies
pydot = ">=4.0.1,<5"
pyqtwebengine = ">=5.15.11,<6"
pyside6 = ">=6.10.2,<7"
pytest = "<9.1.0"  # Gets around error with ament running pytest on newer versions
scipy = ">=1.18.0,<2"

# ROS dependencies
colcon-common-extensions = "*"
ros-jazzy-ros-base = "*"
ros-jazzy-moveit-msgs = "*"
ros-jazzy-nav2-msgs = "*"
ros-jazzy-control-msgs = "*"
ros-jazzy-controller-manager-msgs = "*"
